title: Theory/Simplified
theme: minima

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
header_pages: []
minima:
  nav_pages: []
head_scripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
